version: "3"

services:
    redis:
        image: redis:5.0.5-alpine
        working_dir: /var/lib/redis
        volumes:
            - redis_data:/var/lib/redis
        command: redis-server --appendonly yes
        restart: always

    app:
        build: ./
        ports:
            - 8080:8080
        depends_on:
            - redis
        env_file: 
            - ./.env           
        restart: always

volumes:
    redis_data:
        driver: local